spring.application.name=toolboxcr
#Puerto Escogido
server.port=9202
#Conexión a la BD en la nube toolboxcr en MySQL
spring.datasource.url=jdbc:mysql://mysql-1279609f-proyectofinaldesarolloweb-05ae.f.aivencloud.com:20371



#Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=asdasdasdasdasdasdasd-86873.firebasestorage.app
firebase.storage.path=toolboxcr
firebase.json.path=firebase
firebase.json.file=asdasdasdasdasdasdasd-86873-firebase-adminsdk-fbsvc-2978d5252b.json