spring.application.name=toolboxcr
#Puerto Escogido
server.port=9202
#Conexión a la BD en la nube toolboxcr en MySQL
spring.datasource.url=jdbc:mysql://mysql-1279609f-proyectofinaldesarolloweb-05ae.f.aivencloud.com:20371/ferreteria_web

#Usuario y clave de creaTablas.sql
spring.datasource.username=ferreteria_app
spring.datasource.password=CambiarEstaClave123!
 
#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=asdasdasdasdasdasdasd-86873.firebasestorage.app
firebase.storage.path=toolboxcr
firebase.json.path=firebase
firebase.json.file=asdasdasdasdasdasdasd-86873-firebase-adminsdk-fbsvc-2978d5252b.json